#+PROPERTY: header-args :results verbatim :dir ./

* freeCodeCamp  

**  [[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting][Basic algorithm scripting]]


*** [[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/convert-celsius-to-fahrenheit][Convert Celsius to Fahrenheit]]


**** Description  

#+BEGIN_QUOTE
The algorithm to convert from Celsius to Fahrenheit is the temperature 
in Celsius times 9/5, plus 32.

You are given a variable celsius representing a temperature in Celsius. 
Use the variable fahrenheit already defined and assign it the Fahrenheit temperature
equivalent to the given Celsius temperature. 

Use the algorithm mentioned above to help convert the Celsius temperature to Fahrenheit.

Don't worry too much about the function and return statements as they will be covered in future challenges. For now, only use operators that you have already learned.
#+END_QUOTE   


**** Tests 

#+BEGIN_QUOTE
convertToF(0)   should return a number

convertToF(0)   should return a value  of  32

convertToF(30)  should return a value  of  86

convertToF(-30) should return a value  of -22

convertToF(-10) should return a value  of  14

convertToF(20)  should return a value  of  68
#+END_QUOTE



**** Function

#+BEGIN_SRC js :noweb yes :tangle ./functions/convertToF.js 
/**
 * 
 * @param   {number}  celsius 
 * @returns {number}  number 
 */

function convertToF(celsius) {
  let fahrenheit = 32;
  return  (celsius * 9/5) + fahrenheit;
}

module.exports = convertToF;
#+END_SRC


**** Tape 


#+BEGIN_SRC js :mkdirp yes :noweb yes :tangle ./tests/convertToF.spec.js 
const test = require("tape");
let convertToF = require("../functions/convertToF.js");

test('convertToF test', function (t) {

 t.plan(6);
 t.equal(typeof convertToF(0),'number' ,'convertToF(0) should be a number' );
 t.equal(convertToF(0)   ,32,  "convertToF(0)   should return a value  of  32");
 t.equal(convertToF(30)  ,86,  "convertToF(30)  should return a value  of  86");
 t.equal(convertToF(-30) ,-22, "convertToF(-30) should return a value  of -22");
 t.equal(convertToF(-10) ,14,  "convertToF(-10) should return a value  of  14");
 t.equal(convertToF(20)  ,68,  "convertToF(20)  should return a value  of  68");
 t.end();
});
#+END_SRC

  

#+BEGIN_SRC sh :results value verbatim  :exports results
node ./tests/convertToF.spec.js;
#+END_SRC 

#+RESULTS:
#+begin_example
TAP version 13
# convertToF test
ok 1 convertToF(0) should be a number
ok 2 convertToF(0) should return a value of 32
ok 3 convertToF(30) should return a value of 86
ok 4 convertToF(-30) should return a value of -22
ok 5 convertToF(-10) should return a value of 14
ok 6 convertToF(20) should return a value of 68

1..6
# tests 6
# pass  6

# ok

#+end_example

